apiVersion: ingress.wusy.tech/v1beta1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-demo
  name: app-sample
spec:
  # TODO(user): Add fields here
  image: nginx:1.16
  replicas: 2
  enable_ingress: true
  enable_service: true
