# permissions for end users to edit httpclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: httpclient-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: httpclient
    app.kubernetes.io/part-of: httpclient
    app.kubernetes.io/managed-by: kustomize
  name: httpclient-editor-role
rules:
- apiGroups:
  - apps.github.io
  resources:
  - httpclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.github.io
  resources:
  - httpclients/status
  verbs:
  - get
